"""
AI-fill metadata extraction endpoint.

Merged from the former standalone ``ai_fill_service`` into the backend so that
the entire API surface lives behind a single FastAPI process.
"""

import json
import logging
import os
import re
from pathlib import Path
from typing import Dict, List

from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from groq import Groq

from src.services.adapter_parsing_service import AdapterParsingService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ai-fill", tags=["ai-fill"])

# ---------------------------------------------------------------------------
# Groq client
# ---------------------------------------------------------------------------
_groq_key = os.getenv("GROQ_API_KEY")
if not _groq_key:
    raise RuntimeError("GROQ_API_KEY is not set. Add it to .env")

SYSTEM_PROMPT = os.getenv(
    "AI_FILL_SYSTEM_PROMPT",
    "You are a metadata extraction assistant. Extract metadata from file content.",
)

groq_client = Groq(api_key=_groq_key)

MAX_TEXT_LENGTH = 30_000

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
TYPE_MAP: Dict[str, str] = {
    "str": "string",
    "int": "integer number",
    "float": "decimal number",
    "bool": "boolean (true/false)",
    "datetime": "ISO 8601 datetime string",
    "list": "array of strings",
}


def _normalize_schema(raw: dict) -> dict:
    """Convert the metadata_schema stored in DB to a consistent dict of
    ``{field: {type, required, default}}``."""
    out: Dict = {}
    for key, spec in raw.items():
        if isinstance(spec, str):
            out[key] = {"type": spec.strip().lower(), "required": False}
        elif isinstance(spec, dict):
            out[key] = {
                "type": spec.get("type", "str").strip().lower(),
                "required": bool(spec.get("required", False)),
                "default": spec.get("default"),
            }
        else:
            out[key] = {"type": "str", "required": False}
    return out


def _build_prompt(schema: dict, file_text: str) -> str:
    """Build the user prompt that combines schema description + file content."""
    schema_lines: List[str] = []
    for field, spec in schema.items():
        type_desc = TYPE_MAP.get(spec["type"], spec["type"])
        req = " (required)" if spec.get("required") else ""
        schema_lines.append(f'  - "{field}": {type_desc}{req}')

    schema_block = "\n".join(schema_lines)
    truncated = file_text[:MAX_TEXT_LENGTH]
    if len(file_text) > MAX_TEXT_LENGTH:
        truncated += "\n... (content truncated)"

    return f"""Here is the metadata schema you must fill:

{schema_block}

Rules:
1. Return ONLY a JSON object with exactly these keys — no extra keys, no markdown fences, no explanation.
2. Each value must match the type described above.
3. For "list" fields, return a JSON array of strings.
4. For "bool" fields, return true or false (not strings).
5. For "int" fields, return an integer.
6. For "float" fields, return a number.
7. For "datetime" fields, return an ISO 8601 string.
8. If you cannot determine a value from the file content, use null.

File content:
\"\"\"
{truncated}
\"\"\""""


def _extract_json(text: str) -> dict:
    """Extract JSON from LLM response, handling markdown fences and reasoning blocks."""
    cleaned = text.strip()
    
    # Remove <think>...</think> blocks often generated by reasoning models
    cleaned = re.sub(r"<think>[\s\S]*?</think>", "", cleaned).strip()
    
    fence_match = re.search(r"```(?:json)?\s*([\s\S]*?)```", cleaned)
    if fence_match:
        cleaned = fence_match.group(1).strip()
    else:
        # Fallback to extracting the first {...} or [...] block if no fences
        json_match = re.search(r"(\{[\s\S]*\}|\[[\s\S]*\])", cleaned)
        if json_match:
            cleaned = json_match.group(1).strip()
            
    return json.loads(cleaned)


def _cast_value(value, expected_type: str):
    """Best-effort cast of a value to the expected type."""
    if value is None:
        return None
    match expected_type:
        case "str":
            return str(value)
        case "int":
            return int(float(value)) if not isinstance(value, bool) else int(value)
        case "float":
            return float(value)
        case "bool":
            if isinstance(value, bool):
                return value
            if isinstance(value, str):
                return value.lower() in ("true", "1", "yes")
            return bool(value)
        case "list":
            if isinstance(value, list):
                return [str(v) for v in value]
            if isinstance(value, str):
                return [v.strip() for v in value.split(",") if v.strip()]
            return [str(value)]
        case "datetime":
            return str(value) if value else None
        case _:
            return value


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@router.post("/metadata")
async def ai_fill_metadata(
    file: UploadFile = File(...),
    metadata_schema: str = Form(...),
):
    try:
        schema_raw = json.loads(metadata_schema)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="metadata_schema is not valid JSON")

    if not schema_raw or not isinstance(schema_raw, dict):
        raise HTTPException(status_code=400, detail="metadata_schema must be a non-empty object")

    schema = _normalize_schema(schema_raw)

    raw_data = await file.read()
    ext = Path(file.filename or "").suffix.lower()

    try:
        file_text = AdapterParsingService.get_adapter(ext, raw_data)
    except ValueError:
        try:
            file_text = raw_data.decode("utf-8", errors="replace")
        except Exception:
            raise HTTPException(
                status_code=422,
                detail=f"Cannot extract text from file type '{ext}'",
            )

    if not file_text or not file_text.strip():
        raise HTTPException(status_code=422, detail="No text content could be extracted from the file")

    prompt = _build_prompt(schema, file_text)

    try:
        completion = groq_client.chat.completions.create(
            model="qwen/qwen3-32b",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.1,
            max_completion_tokens=2048,
        )
        raw_output = completion.choices[0].message.content or ""
    except Exception as exc:
        logger.exception("Groq API call failed")
        raise HTTPException(status_code=502, detail=f"Groq API error: {exc}")

    try:
        parsed = _extract_json(raw_output)
    except (json.JSONDecodeError, ValueError):
        logger.error("LLM returned non-JSON: %s", raw_output[:500])
        raise HTTPException(
            status_code=502,
            detail="LLM did not return valid JSON. Try again.",
        )

    metadata_value: Dict = {}
    warnings: List[str] = []
    for field, spec in schema.items():
        raw_val = parsed.get(field)
        try:
            metadata_value[field] = _cast_value(raw_val, spec["type"])
        except (ValueError, TypeError):
            metadata_value[field] = None
            warnings.append(
                f"Field '{field}': could not cast '{raw_val}' to {spec['type']}, set to null"
            )

    return {"metadata_value": metadata_value, "warnings": warnings}
